DROP TABLE IF EXISTS `ci_sessions`;
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `session_id` VARCHAR(40) NOT NULL DEFAULT '0',
  `peopleid` INT(11) NOT NULL,
  `ip_address` VARCHAR(16) NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(50) NOT NULL,
  `last_activity` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `LEFT` INT(11) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 
DROP TABLE IF EXISTS `domains`;
CREATE TABLE IF NOT EXISTS `domains` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `registrar` VARCHAR(100) NOT NULL,
  `dateregd` INT(11) NOT NULL DEFAULT '0',
  `cost` FLOAT NOT NULL DEFAULT '0',
  `regdfor` INT(11) NOT NULL DEFAULT '0',
  `notes` BLOB NOT NULL,
  `pw` VARCHAR(25) NOT NULL,
  `un` VARCHAR(25) NOT NULL,
  `lastupdate` INT(11) NOT NULL DEFAULT '0',
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=10;
 
DROP TABLE IF EXISTS `events`;
CREATE TABLE IF NOT EXISTS `events` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL DEFAULT 'not set',
  `type` ENUM('test','alert','report') NOT NULL,
  `testid` INT(10) NOT NULL,
  `siteid` INT(10) NOT NULL,
  `userid` INT(10) NOT NULL,
  `reported` INT(11) NOT NULL,
  `result` BLOB NOT NULL,
  `TIME` INT(11) NOT NULL,
  `timetaken` FLOAT NOT NULL,
  `isalert` VARCHAR(2) NOT NULL,
  `emailid` INT(11) NOT NULL,
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=69;
 
DROP TABLE IF EXISTS `frequencies`;
CREATE TABLE IF NOT EXISTS `frequencies` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 
DROP TABLE IF EXISTS `hosts`;
CREATE TABLE IF NOT EXISTS `hosts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cost` FLOAT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `hosturl` VARCHAR(100) NOT NULL,
  `un` VARCHAR(50) NOT NULL,
  `pw` VARCHAR(50) NOT NULL,
  `ns1url` VARCHAR(36) NOT NULL,
  `ns1ip` VARCHAR(36) NOT NULL,
  `ns2url` VARCHAR(36) NOT NULL,
  `ns2ip` VARCHAR(36) NOT NULL,
  `ftpurl` VARCHAR(100) NOT NULL,
  `ftpserverip` VARCHAR(36) NOT NULL,
  `ftpun` VARCHAR(50) NOT NULL,
  `ftppw` VARCHAR(50) NOT NULL,
  `cpurl` VARCHAR(36) NOT NULL,
  `cpun` VARCHAR(36) NOT NULL,
  `cppw` VARCHAR(36) NOT NULL,
  `pop3server` VARCHAR(36) NOT NULL,
  `servicetel` VARCHAR(50) NOT NULL,
  `servicetel2` VARCHAR(50) NOT NULL,
  `serviceemail` VARCHAR(100) NOT NULL,
  `webroot` VARCHAR(48) NOT NULL,
  `absoluteroot` VARCHAR(48) NOT NULL,
  `cgiroot` VARCHAR(48) NOT NULL,
  `booked` INT(11) NOT NULL,
  `duration` INT(11) NOT NULL,
  `lastupdate` INT(11) NOT NULL DEFAULT '0',
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=6;
 
DROP TABLE IF EXISTS `people`;
CREATE TABLE IF NOT EXISTS `people` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(25) NOT NULL,
  `pw` VARCHAR(25) NOT NULL,
  `status` SMALLINT(3) NOT NULL DEFAULT '1',
  `name` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `lastupdate` INT(11) NOT NULL DEFAULT '0',
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=5;
 
DROP TABLE IF EXISTS `sites`;
CREATE TABLE IF NOT EXISTS `sites` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `un` VARCHAR(50) NOT NULL,
  `pw` VARCHAR(50) NOT NULL,
  `client1` INT(10) NOT NULL DEFAULT '0',
  `client2` INT(10) NOT NULL DEFAULT '0',
  `admin1` INT(10) NOT NULL DEFAULT '0',
  `admin2` INT(10) NOT NULL DEFAULT '0',
  `domainid` INT(10) NOT NULL DEFAULT '0',
  `hostid` INT(10) NOT NULL DEFAULT '0',
  `webroot` VARCHAR(50) NOT NULL,
  `files` TEXT NOT NULL,
  `filesdate` INT(11) NOT NULL DEFAULT '0',
  `lastupdate` INT(11) NOT NULL DEFAULT '0',
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=15;
 
DROP TABLE IF EXISTS `tests`;
CREATE TABLE IF NOT EXISTS `tests` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `siteid` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(250) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `url` VARCHAR(120) NOT NULL,
  `regex` VARCHAR(250) NOT NULL,
  `p1` VARCHAR(250) NOT NULL,
  `p2` VARCHAR(250) NOT NULL,
  `p3` VARCHAR(250) NOT NULL,
  `p4` VARCHAR(250) NOT NULL,
  `p5` VARCHAR(250) NOT NULL,
  `p6` VARCHAR(250) NOT NULL,
  `frequency` INT(10) NOT NULL DEFAULT '0',
  `lastdone` INT(10) NOT NULL DEFAULT '0',
  `isalert` VARCHAR(2) NOT NULL,
  `setup` INT(10) NOT NULL DEFAULT '0',
  `lastupdate` INT(10) NOT NULL DEFAULT '0',
  `notes` VARCHAR(250) NOT NULL,
  `submit` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=11;
 
DROP TABLE IF EXISTS `types`;
CREATE TABLE IF NOT EXISTS `types` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;